type: release
name: dm_deploy
version: 0.1
description: Data Management Services
ion: 0.0.1
apps:
  ##################################
  # CORE SERVICES
  # Bootstrap processes perform initializations
  ##################################

  - name: event_persister
    processapp: [event_persister, ion.processes.event.event_persister, EventPersister]
    bootlevel: 1

  - name: bootstrapper1
    processapp: [bootstrapper1, ion.processes.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 2
    config:
      bootstrap_plugins:
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_core, BootstrapCore]

  - name: directory
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]
    bootlevel: 10

  - name: resource_registry
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]
    bootlevel: 10

  - name: identity_management
    processapp: [identity_management, ion.services.coi.identity_management_service, IdentityManagementService]
    bootlevel: 10

  - name: policy_management
    processapp: [policy_management, ion.services.coi.policy_management_service, PolicyManagementService]
    bootlevel: 10

  - name: exchange_management
    processapp: [exchange_management, ion.services.coi.exchange_management_service, ExchangeManagementService]
    bootlevel: 10

  - name: org_management
    processapp: [org_management, ion.services.coi.org_management_service, OrgManagementService]
    bootlevel: 10


  ##################################
  # HIGHER LEVEL SERVICES
  ##################################

  ##### COI SERVICES
#  - name: agent_management
#    processapp: [agent_management, ion.services.coi.agent_management_service, AgentManagementService]
#
#  - name: conversation_management
#    processapp: [conversation_management, ion.services.coi.conversation_management_service, ConversationManagementService]
#
#  - name: object_management
#    processapp: [object_management, ion.services.coi.object_management_service, ObjectManagementService]
#
#  - name: resource_management
#    processapp: [resource_management, ion.services.coi.resource_management_service, ResourceManagementService]
#
#  - name: service_management
#    processapp: [service_management, ion.services.coi.service_management_service, ServiceManagementService]


  #### CEI Services
#  - name: epu_management
#    processapp: [epu_management, ion.services.cei.epu_management_service, EpuManagementService]
#
#  - name: execution_engine_management
#    processapp: [execution_engine_management, ion.services.cei.execution_engine_management_service, ExecutionEngineManagementService]
#
  - name: process_dispatcher
    processapp: [process_dispatcher, ion.services.cei.process_dispatcher_service, ProcessDispatcherService]
    bootlevel: 10
#
#  - name: provisioner
#    processapp: [provisioner, ion.services.cei.provisioner_service, ProvisionerService]
#
#  - name: taskable_resource_management
#    processapp: [taskable_resource_management, ion.services.cei.taskable_resource_management_service, TaskableResourceManagementService]
#
#  - name: taskable_resource_planner
#    processapp: [taskable_resource_planner, ion.services.cei.taskable_resource_planner_service, TaskableResourcePlannerService]


  #### DM Services
  - name: pubsub_management
    processapp: [pubsub_management, ion.services.dm.distribution.pubsub_management_service, PubsubManagementService]
    bootlevel: 10

  - name: dataset_management
    processapp: [dataset_management, ion.services.dm.inventory.dataset_management_service, DatasetManagementService]
    bootlevel: 10

  - name: ingestion_management
    processapp: [ingestion_management, ion.services.dm.ingestion.ingestion_management_service, IngestionManagementService]
    bootlevel: 10

  - name: data_retriever
    processapp: [data_retriever, ion.services.dm.inventory.data_retriever_service, DataRetrieverService]
    bootlevel: 10

  - name: index_management
    processapp: [index_management, ion.services.dm.inventory.index_management_service, IndexManagementService]
    bootlevel: 10

  - name: user_notification
    processapp: [user_notification, ion.services.dm.presentation.user_notification_service, UserNotificationService]
    bootlevel: 10

  #- name: preservation_management
  #  processapp: [preservation_management, ion.services.dm.preservation.preservation_management_service, PreservationManagementService]
  #  bootlevel: 10

  - name: catalog_management
    processapp: [catalog_management, ion.services.dm.presentation.catalog_management_service, CatalogManagementService]
    bootlevel: 10

  - name: discovery
    processapp: [discovery, ion.services.dm.presentation.discovery_service, DiscoveryService]
    bootlevel: 10


  - name: bootstrapper2
    processapp: [bootstrapper2, ion.processes.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 20
    config:
      bootstrap_plugins:
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_org, BootstrapOrg]
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_policy, BootstrapPolicy]
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_process_dispatcher, BootstrapProcessDispatcher]
          config:
            bootstrap:
              processes:
                ingestion:
                  datastore_name: datasets
                  queue_name:     science_data.science_granule_ingestion
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_transform, BootstrapTransform]
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_index, BootstrapIndex]
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_ingestion, BootstrapIngestion]
          config:
            ingestion:
              exchange_point: science_data
              queues:
                - name: science_granule_ingestion
                  type: SCIDATA
                  datastore_name: datasets
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_service, BootstrapService]

  # LAST SERVICE GATEWAY SERVICE
  - name: service_gateway
    processapp: [service_gateway, ion.services.coi.service_gateway_service, ServiceGatewayService]
    bootlevel: 30
